# Generated by Django 4.2.4 on 2023-08-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='num',
            field=models.IntegerField(verbose_name='手机'),
        ),
    ]
